### ISSUE TITLE
No dark mode in chat popout

### ISSUE THREAD

**Issue by azizLIGHT** [howar31/EzTwitch#4]
The chat popout gives a white screen background and is not capable of being themed. There is no option to use Dark Mode because it is using the embedded URL rather than the popout URL. The chat URL being used is https://www.twitch.tv/embed/forsen/chat . However, the other URL https://www.twitch.tv/popout/forsen/chat?popout= has options to enable dark mode. Is it possible to change the url for the chat popout for us dark mode users?

Thanks

**Comment by howar31** [comment]
This issue is fixed in v1.2.4 and it's out now.  Thanks for reporting!

**Comment by azizLIGHT** [comment]
Thanks for fixing everything!
